export const homeObjOne = {
    id: 'home',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: '#Truth',
    headline: 'Benchmark',
    description: 'The goal of this study is to create a system that can establish an optimized NLP algorithm for the researchers dataset in order to offer accurate and precise results. This research also focuses on developing a dataset that will be used to evaluate various NLP algorithms.',
    buttonLabel: 'Benchmark',
    imgStart: false,
    img: require('../../images/news.svg').default,
    alt: 'Online articles',
    dark: true,
    primary: true,
    darkText: false,
}
export const homeObjTwo = {
    id: 'search',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: '#Enlightenment',
    headline: 'Search',
    description: 'Determining if a news is fake can be as easy as doing a Google search. Otherwise, further investigation is needed. Some false stories may contain a grain of truth or may be the result of a misunderstanding. Our mission is to find out the truth.',
    buttonLabel: 'Search',
    imgStart: true,
    img: require('../../images/search.svg').default,
    alt: 'Search',
    dark: false,
    primary: false,
    darkText: true,
}
export const homeObjThree = {
    id: 'school',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: '#DLSUD',
    headline: 'School',
    description: 'DLSU-D takes an unconventional approach to education, allowing students to learn in a natural setting and instilling not only the Lasallian values of faith, zeal, and service in them, but also allowing them to experience and participate in socially responsible projects throughout their time at the university.',
    buttonLabel: 'School',
    imgStart: false,
    img: require('../../images/school.svg').default,
    alt: 'School',
    dark: true,
    primary: true,
    darkText: false,
}